[package]
name = "librust"
version = "0.1.0"
edition = "2024"

[lib]
name = "librust"
crate-type = ["lib", "staticlib", "cdylib"]


[dependencies]
uniffi = { version = "0.29", default-features = false, features = ["ffi-trace"]}
